development:
  host: localhost
  database: twietry_development

test:
  host: localhost
  database: twietry_test

# set these environment variables on your prod server
production:
  host: <%= ENV['TWIETRY_MONGOID_HOST'] %>
  port: <%= ENV['TWIETRY_MONGOID_PORT'] %>
  username: <%= ENV['TWIETRY_MONGOID_USER'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['TWIETRY_MONGOID_DB'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
