development:
  host: localhost
  database: twietry_development

test:
  host: localhost
  database: twietry_test

# set these environment variables on your prod server
production:
  host: localhost
  #<%= ENV['MONGOID_HOST'] %>
  #port: <%= ENV['MONGOID_PORT'] %>
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  database: i_love_the_rain
  #<%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
